var config=
{
	"code":"emotionAnalysis",
	"inputinfo":
	[
		 {
			 dataName:"data1", 
			 dataType:"binary/text/gzip", 
			 encoding:"/UTF-8/GBK", 
			 dataDir:"/user/yimr/abc", 
			 dataRange:"dirname_time_rule/filename_time_rule/all/filename_rule/dirname_rule",
			 dataRangeDetail:{
				 //当选择的数据范围
				 //为dirname_time_rule时，与dirnameTimeRule，timeRangeFrom，timeRangeTo，timeUnit，filenameMatch，filenameNotMatch
				 //为filename_time_rule时，与filenameTimeRule，timeRangeFrom，timeRangeTo，timeUnit，filenameNotMatch
				 //为filename_rule时，与filenameMatch，filenameNotMatch
				 //为dirname_rule时，与filenameMatch，filenameNotMatch
				 //为all时，都不相关
				 dirnameTimeRule:"dir@{yyyyMMdd}",
				 timeRangeFrom:"",
				 timeRangeTo:"",
				 timeUnit:"second/minute/hour/day",
				 filenameMatch:"abc.*",
				 filenameNotMatch:"abc.kk*",
				 filenameTimeRule:"dir@{yyyyMMdd}"
			 },
			 colDelimitType:"FIELD/REGEX",
			 colDelimitExpr:"分隔符，或者正则",
			 colCount:"20",
			 //多行日志合并
			 multilineCombine:"0/1",
			 combineRegex:"",
			 colDetail:[
			            {
			            	name:"",
			            	type:"string/int/double/date/long/timestamp",
			            	dateFormat:""
			            }
			  ]
		 }
	],
	"config":
		{
			"vcol":[
			        {//一个计算字段，只支持对一个源数据的转换，不可混用
			        	colName:"abc", 
			        	funcName:"", 
			        	args:[
			        	      {
			        	    	  desc:"",
			        	    	  type:"field/string/int/fieldlist/float"
			        	      }
			            ],
			            //仅当自定义时需要
			            returnType:""
			        },
			 ],
			"relation":{
				type:"join/union",
				unionDetail:
					{
						data1:[col1,col2,vcol21],
						data2:[col2,vcol21,col4]
					},
				joinDetail:
					{
						relation:[//N份数据，至少有N-1个关系
						          {
						        	  left:data1, 
						        	  op:"inner/outer/left/right", 
						        	  right:data2, 
						        	  cond:[
						              	{
						              		left:data2.col2, 
						              		right:data1.vcol2 
						              	}
						              ]
						          }
						  ]
					}
			},
			"filter":[
			          //按以前，娟姐提供
			          
			          ]
		},
	"storeinfo":[
	             	{
	             		dataType:"text/gzip", 
	             		paDataDir:"/user/yimr/abc", 
	             		colDelimitExpr:"\t", 
	             		dataDir:"abc@{yyyyMMdd -86400s}", 
	             		outrowfilter:"yes/no",
	             		outrowfilterType:"and/or",
	             		rowfilterDetail:[
	             			{
	             				left:data2.col2, 
	             				op:">/</=/>=/<=/d>/d</d=/d>=/d<=/isnull/notnull/contain/notcontain/", 
	             				value:""
	             			}
	             		],
	             		outCols:[data1.col3,data3.col2]
	             	}
	             ]		
};